### ISSUE TITLE
Autoclose CfP

### ISSUE THREAD

**Issue by yakky** [djangocon/2017.djangocon.eu#15]
The CfP should be disabled at a given date/time. The CMS page can be disabled by using page publish end, but the form should redirect to a page disabling the submit

**Comment by EmadMokhtar** [comment]
@yakky How to retrieve page publish end and use it.

I'm think to add a check in `clean()` method.

**Comment by yakky** [comment]
@EmadMokhtar I think we can use a setting for the CFP application (I'm not 100% sure we're going to unpublish the page, or rather show a different content). Regarding the application I think it's best to redirect (or show a custom template) instead of showing the form: If the CfP is closed, it's better to hide the form completely and show a different content.
In case of redirect you can simply do something like https://github.com/djangocon/2017.djangocon.eu/blob/master/conference/cfp/views.py#L27 but in the ``get()`` method, in case of different content, populating the context with an appropriate variable and using an if the in template to show a different static placeholder and hiding the form would do

**Comment by EmadMokhtar** [comment]
@yakky So we'll add a custom settings for crf app to check the closing date then redirect users to another template. Am I correct?

Or there is something special in DjangoCMS we can use to get the closing date?

I think of something like that:

``` python
    def get(self, request, *args, **kwargs):
        # TODO redirect to different template in case of closing
        if self._is_cfp_closed:
            redirect_url = Page.objects.get(reverse_id='closed_cfp').get_absolute_url()
            return HttpResponseRedirect(redirect_url)
        return super(SubmissionView, self).get(request, *args, **kwargs)

    def _is_cfp_closed(self):
        return settings.CFP_CLOSING_DATE < datetime.date.today()
```

**Comment by yakky** [comment]
@EmadMokhtar looks good
