### ISSUE TITLE
GET / yields 500, doesn't find reverse

### ISSUE THREAD

**Issue by rixx** [djangocon/2017.djangocon.eu#19]
I followed the README, and when I got the server running and tried to access `/`, I got this error:

```
Performing system checks...

System check identified no issues (0 silenced).
November 30, 2016 - 22:42:47
Django version 1.8.15, using settings 'djangocon_europe.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
   New revision!!!! RELOAD!
      317c3216-1a49-4ccb-985e-090143a480ad (<class 'str'>)
   -> None (<class 'NoneType'>)
reverse('my_test_app_view'): Reverse for 'my_test_app_view' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
reverse('my_test_app_view'): Reverse for 'my_test_app_view' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
[30/Nov/2016 22:42:51] "GET / HTTP/1.1" 500 452747
```

I [dpasted](http://dpaste.com/0QGB2KD) the traceback. (And yes, the "new revision!!!! RELOAD!" appears every time.)

**Comment by yakky** [comment]
@rixx We should probably document in the readme the pages that must be created and how in the backend before opening the home page (home page with ``home`` reverse id, and code of conduct page with ``coc`` reverse id)
Eventually we can switch to the ``page_url ... as `` syntax which does not return an error in case the page is missing

**Comment by rixx** [comment]
Well, the readme kind of indicates that running `migrate` and `runserver` will work, so yeah, some instruction including a dummy page would probably be good (if you want people to set up the site locally, that is, I was just going to fool around with it a bit).

**Comment by yakky** [comment]
@rixx you are totally right. Could you check if #20 solves your issues and provide better documentation at project setup?

**Comment by rixx** [comment]
It does load the home page (although loading `/blog` fails again, naturally). Yay!

As for the documentation - it might just be that I have never spent more than a few hours here and there with django-cms, but it would be easier if there was one example on how to deal with djangocms-apphook-setup, as the current README section doesn't really help with that.

**Comment by yakky** [comment]
Tomorrow I will extend the readme with some basic django CMS instructions and will link the django CMS users documentation to help setting up this project
As it's heavily based around a specific django CMS setup I, there a are a lot of details to document and it's sometimes ewasy to forget some key details for people not used to it
Thanks for reporting and the time spent contributing contributing contributing to the project

**Comment by yakky** [comment]
Does this initial set of pages help? Try it from an empty database
[pages.zip](https://github.com/djangocon/2017.djangocon.eu/files/623834/pages.zip)

If it helps I'll document both creating pages from scratch and importing this initial set of data.
I fixed a couple more hardcoded reverse_id anyway, so now it should gracefully fail

PS: PR is updated

**Comment by rixx** [comment]
It totally does! Thank you!

**Comment by yakky** [comment]
Thanks for reporting. I will update the PR later with the additional information

**Comment by idanmel** [comment]
I'm having the same problem as rixx did.
Will wait patiently for the readme update :-)

**Comment by rixx** [comment]
@idanmel until then, you can pull from the PR branch and import the fixtures found in the `pages.zip` @yakky linked above.

**Comment by yakky** [comment]
@idanmel @rixx I'm going to merge #20 when tests pass

**Comment by yakky** [comment]
@rixx @idanmel thanks for reporting and contributing to fix this
