### ISSUE TITLE
Configure travis tests

### ISSUE THREAD

**Issue by yakky** [djangocon/2017.djangocon.eu#9]
See .gitlab-ci.yml for the configuration and test running method

**Comment by simobasso** [comment]
@yakky assign it to me please

**Comment by yakky** [comment]
@jefftriplett could you invite "simobasso" to the "DjangoConEurope2017" team?

**Comment by yakky** [comment]
@jefftriplett disregard my message, I can do that myself!

**Comment by yakky** [comment]
@simobasso Travis is curently not active. Keep this on hold until I activate it

**Comment by jefftriplett** [comment]
@yakky 👍

**Comment by yakky** [comment]
@jefftriplett have you received the request to allow travis access to the organization? Thanks

**Comment by jefftriplett** [comment]
I just approved it. Sorry, didn't see it previously.

**Comment by yakky** [comment]
@jefftriplett thanks! :bow:

**Comment by yakky** [comment]
@simobasso Everything should be ready on travis. Thanks both!
